"""Framework-independent ForgeAI Brain domain model."""

from .events import EventEnvelope, new_event
from .lifecycle import CapabilityLifecycleError, required_policy_action, transition
from .models import (
    ArtifactReference,
    CapabilityCandidate,
    CapabilityDescriptor,
    CapabilityRecord,
    CapabilityRequirement,
    CapabilityStatus,
    PluginManifest,
    PluginRuntime,
    PolicyAction,
    PolicyDecision,
    PolicyDecisionKind,
    PolicyRequest,
    RiskLevel,
    TrustTier,
)
from .workflow import (
    PlannedWorkflowTask,
    SelectedCapability,
    UnsatisfiedRequirement,
    WorkflowDefinition,
    WorkflowGoal,
    WorkflowPlan,
    WorkflowPlanStatus,
    WorkflowTaskDefinition,
    WorkflowValidationError,
)
from .knowledge import (
    KnowledgeChunk,
    KnowledgeDocument,
    KnowledgeIngestRequest,
    KnowledgeQuery,
    KnowledgeSearchResult,
    KnowledgeSourceReference,
    KnowledgeValidationError,
)
from .memory import (
    MemoryQuery,
    MemoryRecord,
    MemoryScope,
    MemorySearchResult,
    MemorySensitivity,
    MemoryValidationError,
    MemoryWriteRequest,
)

__all__ = [
    "ArtifactReference",
    "CapabilityCandidate",
    "CapabilityDescriptor",
    "CapabilityLifecycleError",
    "CapabilityRecord",
    "CapabilityRequirement",
    "CapabilityStatus",
    "EventEnvelope",
    "PluginManifest",
    "PluginRuntime",
    "PolicyAction",
    "PolicyDecision",
    "PolicyDecisionKind",
    "PolicyRequest",
    "RiskLevel",
    "TrustTier",
    "PlannedWorkflowTask",
    "SelectedCapability",
    "UnsatisfiedRequirement",
    "WorkflowDefinition",
    "WorkflowGoal",
    "WorkflowPlan",
    "WorkflowPlanStatus",
    "WorkflowTaskDefinition",
    "WorkflowValidationError",
    "KnowledgeChunk",
    "KnowledgeDocument",
    "KnowledgeIngestRequest",
    "KnowledgeQuery",
    "KnowledgeSearchResult",
    "KnowledgeSourceReference",
    "KnowledgeValidationError",
    "MemoryQuery",
    "MemoryRecord",
    "MemoryScope",
    "MemorySearchResult",
    "MemorySensitivity",
    "MemoryValidationError",
    "MemoryWriteRequest",
    "new_event",
    "required_policy_action",
    "transition",
]
