#!/usr/bin/env python3
"""
Kaggle CLI Setup Helper

Sets up the Kaggle command-line tool for this project.
- Detects Kaggle CLI binary dynamically (no hardcoded paths)
- Validates kaggle.json API key format
- Creates kaggle.cmd wrapper in project root
- Tests connectivity
- Lists your notebooks
"""

import json
import os
import shutil
import subprocess
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent.parent
KAGGLE_JSON_PATH = Path.home() / ".kaggle" / "kaggle.json"
REPO_PATH = PROJECT_ROOT / "tools" / "kaggle-cli"


def find_kaggle_bin() -> Path | None:
    """Find kaggle executable dynamically (checks PATH, pip install dirs, etc.)."""
    # 1. Check PATH
    which = shutil.which("kaggle")
    if which:
        return Path(which)
    # 2. Check pip user site
    try:
        import site
        user_scripts = Path(site.USER_BASE) / "Scripts" / "kaggle.exe"
        if user_scripts.exists():
            return user_scripts
    except Exception:
        pass
    # 3. Check common locations
    candidates = [
        Path(os.environ.get("APPDATA", "")) / "Python" / s / "Scripts" / "kaggle.exe"
        for s in os.listdir(Path(os.environ.get("APPDATA", "")) / "Python")
        if s.startswith("Python")
    ] if os.environ.get("APPDATA") else []
    candidates += [
        Path(sys.exec_prefix) / "Scripts" / "kaggle.exe",
        Path(sys.base_prefix) / "Scripts" / "kaggle.exe",
    ]
    for c in candidates:
        if c.exists():
            return c
    return None


def create_kaggle_cmd(kaggle_bin: Path) -> None:
    """Create a kaggle.cmd wrapper in the project root for easy access."""
    cmd_path = PROJECT_ROOT / "kaggle.cmd"
    if cmd_path.exists():
        return
    content = f"""@echo off
REM Kaggle CLI wrapper - auto-generated by scripts/kaggle_setup.py
"{kaggle_bin}" %*
"""
    cmd_path.write_text(content, encoding="utf-8")
    print(f"[OK] Created wrapper: {cmd_path}")
    print("    Now you can run:  kaggle commands  from any terminal in this project")


def print_banner(text: str) -> None:
    print(f"\n{'='*60}")
    print(f"  {text}")
    print(f"{'='*60}")


def check_kaggle_installed() -> tuple[bool, Path | None]:
    """Check if kaggle CLI is installed. Returns (ok, path)."""
    kaggle_bin = find_kaggle_bin()
    if kaggle_bin:
        print(f"[OK] Kaggle CLI found at: {kaggle_bin}")
        return True, kaggle_bin
    print("[X] Kaggle CLI not found. Installing...")
    result = subprocess.run(
        [sys.executable, "-m", "pip", "install", "kaggle", "--quiet", "--user"],
        capture_output=True, text=True
    )
    if result.returncode == 0:
        kaggle_bin = find_kaggle_bin()
        if kaggle_bin:
            print(f"[OK] Kaggle CLI installed at: {kaggle_bin}")
            return True, kaggle_bin
    print(f"[X] Installation failed: {result.stderr[:300]}")
    return False, None


def check_api_key() -> bool:
    """Check if kaggle.json exists AND has valid JSON with username+key."""
    if not KAGGLE_JSON_PATH.exists():
        print("[X] Kaggle API key NOT found!")
        print()
        print("  To create one:")
        print("  1. Go to https://www.kaggle.com -> Login (free)")
        print("  2. Profile -> Settings -> Account -> API section")
        print("  3. Click 'Create New API Token'")
        print(f"  4. Save kaggle.json to: {KAGGLE_JSON_PATH}")
        return False

    try:
        data = json.loads(KAGGLE_JSON_PATH.read_text(encoding="utf-8"))
        if "username" in data and "key" in data:
            print(f"[OK] Kaggle API key valid — user: {data['username']}")
            return True
        else:
            print(f"[X] Invalid kaggle.json: missing 'username' or 'key' fields")
            return False
    except json.JSONDecodeError as e:
        print(f"[X] Invalid kaggle.json: {e}")
        return False


def test_connectivity(kaggle_bin: Path) -> bool:
    """Test Kaggle API connectivity."""
    print_banner("Testing Kaggle API Connectivity")
    try:
        result = subprocess.run(
            [str(kaggle_bin), "competitions", "list", "--max-results", "3"],
            capture_output=True, text=True, timeout=15
        )
        if result.returncode == 0:
            print("[OK] Kaggle API connected successfully!")
            lines = result.stdout.strip().splitlines()
            for line in lines[:5]:
                print(f"  {line}")
            return True
        else:
            print(f"[X] API Error: {result.stderr[:500]}")
            return False
    except subprocess.TimeoutExpired:
        print("[X] Connection timed out. Check internet connectivity.")
        return False
    except Exception as e:
        print(f"[X] Error: {e}")
        return False


def list_notebooks(kaggle_bin: Path) -> None:
    """List user's Kaggle notebooks."""
    print_banner("Your Kaggle Notebooks")
    try:
        result = subprocess.run(
            [str(kaggle_bin), "kernels", "list", "--mine", "--max-results", "10"],
            capture_output=True, text=True, timeout=15
        )
        if result.returncode == 0 and result.stdout.strip():
            lines = result.stdout.strip().splitlines()
            for line in lines[:10]:
                print(f"  {line}")
        elif result.returncode == 0:
            print("  No notebooks yet. Create one at kaggle.com/notebooks")
        else:
            print(f"  Error: {result.stderr[:200]}")
    except Exception as e:
        print(f"  Error: {e}")


def print_version(kaggle_bin: Path) -> None:
    """Print Kaggle CLI version."""
    try:
        result = subprocess.run(
            [str(kaggle_bin), "--version"], capture_output=True, text=True, timeout=10
        )
        ver = result.stdout.strip() or "unknown"
        print(f"Kaggle CLI version: {ver}")
    except Exception:
        pass


def push_notebook(kaggle_bin: Path, notebook_path: str | None = None) -> None:
    """Push the training notebook to Kaggle."""
    if not notebook_path:
        nb = PROJECT_ROOT / "colab_export" / "finetune_qwen14b_unsloth.ipynb"
        if nb.exists():
            notebook_path = str(nb)
        else:
            print("[!] No notebook path provided and colab_export/ not found")
            return
    print(f"\nPushing notebook to Kaggle: {notebook_path}")
    try:
        result = subprocess.run(
            [str(kaggle_bin), "kernels", "push", "-p", notebook_path],
            capture_output=True, text=True, timeout=30
        )
        if result.returncode == 0:
            print(f"[OK] Notebook pushed! View at: https://www.kaggle.com/notebooks")
        else:
            print(f"[X] Push failed: {result.stderr[:500]}")
    except Exception as e:
        print(f"[X] Error: {e}")


def main():
    print_banner("Kaggle CLI Setup - PythonAI Project")
    print(f"Project: {PROJECT_ROOT.name}")
    print(f"Repo:    {REPO_PATH}")
    print(f"Config:  {KAGGLE_JSON_PATH}")
    print()

    # Step 1: Check installation
    installed, kaggle_bin = check_kaggle_installed()
    if not installed or not kaggle_bin:
        print("\nTip: Run: pip install kaggle --user")
        sys.exit(1)
    print_version(kaggle_bin)

    # Step 2: Create wrapper (if not on PATH)
    if not shutil.which("kaggle"):
        create_kaggle_cmd(kaggle_bin)
    print()

    # Step 3: Check API key
    has_key = check_api_key()
    print()

    # Step 4: Test connectivity (only if key exists)
    if has_key:
        test_connectivity(kaggle_bin)
        print()
        list_notebooks(kaggle_bin)
        print_banner("NEXT STEPS")
        print("  Run this to upload your training notebook to Kaggle:")
        print(f"    {kaggle_bin.name} kernels push -p colab_export/finetune_qwen14b_unsloth.ipynb")
        print()
        print("  Or use the project wrapper:")
        print("    kaggle kernels push -p colab_export/finetune_qwen14b_unsloth.ipynb")
    else:
        print_banner("ACTION REQUIRED")
        print("1. Go to https://www.kaggle.com/settings")
        print("2. Click 'Create New API Token' under API section")
        print("3. Save the downloaded kaggle.json to:")
        print(f"   {KAGGLE_JSON_PATH}")
        print("4. Run this script again:")
        print("   python scripts/kaggle_setup.py")


if __name__ == "__main__":
    main()
