"""\
SEAL Types — Shared Dataclasses for the SEAL Dual-Loop (Phase 3)
==================================================================

Implements the type system for the Self-Adapting LLM (SEAL) architecture.

Research: MIT SEAL (NeurIPS 2025)
  "Self-Adapting Language Models via Inner SFT + Outer RL Loop"

Architecture:
  Inner Loop:  SFT on self-generated curriculum → new adapter
  Outer Loop:  RL reward = downstream acceptance rate improvement
  Meta-Learning: Curriculum generator model trained via outer loop reward
"""

from __future__ import annotations

import json
import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class SealActionType(str, Enum):
    """Types of self-edit actions the curriculum generator can emit."""

    GENERATE_EXAMPLES = "generate_examples"
    """Generate N synthetic training examples in a given domain."""

    FOCUS_DOMAIN = "focus_domain"
    """Focus training on a specific domain (e.g. 'error_handling', 'async')."""

    INCREASE_DIFFICULTY = "increase_difficulty"
    """Generate harder examples than the current set."""

    REINFORCE_WEAKNESS = "reinforce_weakness"
    """Generate examples targeting the model's current weak areas."""

    BALANCE_LANGUAGES = "balance_languages"
    """Generate examples for underrepresented languages."""

    REDUCE_HALLUCINATION = "reduce_hallucination"
    """Generate examples that test factual accuracy / grounding."""


@dataclass
class SelfEditAction:
    """A curriculum instruction generated by the model for itself.

    The model generates these as JSON instructions that describe
    what training data to generate next. The inner loop interprets
    this action and generates accordingly.
    """

    action_type: SealActionType
    """What kind of curriculum to generate."""

    domain: str = "general"
    """Subject domain for the action (e.g. 'error_handling', 'async', 'fastapi')."""

    count: int = 20
    """Number of examples to generate."""

    difficulty: str = "medium"
    """Difficulty level: 'easy', 'medium', 'hard'."""

    language: str = "python"
    """Target programming language."""

    focus_areas: list[str] = field(default_factory=list)
    """Specific areas to focus on (e.g. 'type_hints', 'edge_cases')."""

    rationale: str = ""
    """Why is this action beneficial right now? Generated by the model."""

    temperature: float = 0.7
    """Generation temperature for creating examples."""

    @classmethod
    def from_json(cls, text: str) -> SelfEditAction | None:
        """Parse a SelfEditAction from a JSON string.

        Attempts to extract JSON from a code block or raw text.
        Returns None if parsing fails.
        """
        import re

        # Try to find JSON in code block first
        json_match = re.search(r"```(?:json)?\s*\n(.*?)\n```", text, re.DOTALL)
        if json_match:
            text = json_match.group(1)

        # Try direct JSON parse
        try:
            data = json.loads(text.strip())
        except json.JSONDecodeError:
            return None

        # Map action_type string to enum
        action_str = data.get("action", data.get("action_type", ""))
        try:
            action_type = SealActionType(action_str)
        except ValueError:
            action_type = SealActionType.GENERATE_EXAMPLES

        return cls(
            action_type=action_type,
            domain=data.get("domain", "general"),
            count=data.get("count", 20),
            difficulty=data.get("difficulty", "medium"),
            language=data.get("language", "python"),
            focus_areas=data.get("focus_areas", []),
            rationale=data.get("rationale", ""),
            temperature=data.get("temperature", 0.7),
        )

    def to_dict(self) -> dict[str, Any]:
        """Serialize to dictionary."""
        return {
            "action": self.action_type.value,
            "domain": self.domain,
            "count": self.count,
            "difficulty": self.difficulty,
            "language": self.language,
            "focus_areas": self.focus_areas,
            "rationale": self.rationale,
            "temperature": self.temperature,
        }

    def to_json(self) -> str:
        """Serialize to JSON string."""
        return json.dumps(self.to_dict(), indent=2)


@dataclass
class CurriculumState:
    """Tracks the current state of the self-generated curriculum.

    This is persisted between training runs so the system can
    remember what it has already explored and what worked.
    """

    # Cycle tracking
    cycle_number: int = 0
    """Which SEAL cycle we're on (increments each outer loop)."""

    total_actions_taken: int = 0
    """Total number of self-edit actions taken across all cycles."""

    # Domain exploration
    domains_explored: dict[str, int] = field(default_factory=dict)
    """Domain name → number of times explored."""

    difficulties_tried: dict[str, int] = field(default_factory=dict)
    """Difficulty level → number of times used."""

    # Weakness tracking
    weakness_scores: dict[str, float] = field(default_factory=dict)
    """Domain/area → weakness score (higher = more improvement needed)."""

    # Performance history
    acceptance_rate_history: list[dict[str, Any]] = field(default_factory=list)
    """List of {cycle, acceptance_rate, delta} records."""

    # Action effectiveness
    action_effectiveness: dict[str, list[float]] = field(default_factory=dict)
    """Action type → list of reward deltas from using that action."""

    # Best performing configuration
    best_action: dict[str, Any] | None = None
    """The action that produced the best acceptance rate improvement."""

    def to_dict(self) -> dict[str, Any]:
        return {
            "cycle_number": self.cycle_number,
            "total_actions_taken": self.total_actions_taken,
            "domains_explored": dict(self.domains_explored),
            "difficulties_tried": dict(self.difficulties_tried),
            "weakness_scores": dict(self.weakness_scores),
            "acceptance_rate_history": list(self.acceptance_rate_history),
            "action_effectiveness": {k: v for k, v in self.action_effectiveness.items()},
            "best_action": self.best_action,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> CurriculumState:
        return cls(
            cycle_number=data.get("cycle_number", 0),
            total_actions_taken=data.get("total_actions_taken", 0),
            domains_explored=data.get("domains_explored", {}),
            difficulties_tried=data.get("difficulties_tried", {}),
            weakness_scores=data.get("weakness_scores", {}),
            acceptance_rate_history=data.get("acceptance_rate_history", []),
            action_effectiveness=data.get("action_effectiveness", {}),
            best_action=data.get("best_action"),
        )

    def record_action(self, action: SelfEditAction, reward_delta: float):
        """Record the result of taking a curriculum action."""
        self.total_actions_taken += 1

        # Track domain exploration
        domain_key = f"{action.domain}/{action.difficulty}"
        self.domains_explored[domain_key] = self.domains_explored.get(domain_key, 0) + 1

        # Track difficulties
        self.difficulties_tried[action.difficulty] = self.difficulties_tried.get(action.difficulty, 0) + 1

        # Track effectiveness
        action_key = action.action_type.value
        if action_key not in self.action_effectiveness:
            self.action_effectiveness[action_key] = []
        self.action_effectiveness[action_key].append(reward_delta)

        # Track best action
        if self.best_action is None or reward_delta > self.best_action.get("reward_delta", float("-inf")):
            self.best_action = {
                **action.to_dict(),
                "reward_delta": reward_delta,
                "cycle": self.cycle_number,
            }

    def get_best_action_type(self) -> str | None:
        """Return the action type with the highest average reward."""
        if not self.action_effectiveness:
            return None
        best = max(
            self.action_effectiveness,
            key=lambda k: (
                sum(self.action_effectiveness[k]) / len(self.action_effectiveness[k])
                if self.action_effectiveness[k]
                else float("-inf")
            ),
        )
        return best

    def get_underrepresented_domains(self, threshold: int = 2) -> list[str]:
        """Return domains explored fewer than threshold times."""
        return [d for d, count in self.domains_explored.items() if count < threshold]


@dataclass
class RewardRecord:
    """Records the reward signal for a SEAL cycle.

    The outer loop computes this after deploying a new adapter and
    measuring the downstream acceptance rate.
    """

    cycle: int
    """Which SEAL cycle this reward is for."""

    action: SelfEditAction
    """The action that was taken this cycle."""

    acceptance_rate_before: float
    """Acceptance rate before deploying the new adapter."""

    acceptance_rate_after: float
    """Acceptance rate after deploying the new adapter."""

    reward_delta: float = 0.0
    """acceptance_rate_after - acceptance_rate_before."""

    examples_generated: int = 0
    """How many synthetic examples were generated."""

    inner_train_loss: float | None = None
    """Training loss from the inner loop SFT."""

    inner_eval_loss: float | None = None
    """Evaluation loss from the inner loop SFT."""

    timestamp: float = field(default_factory=time.time)

    def __post_init__(self):
        self.reward_delta = self.acceptance_rate_after - self.acceptance_rate_before

    def is_improvement(self) -> bool:
        """Did this cycle improve acceptance rate?"""
        return self.reward_delta > 0

    @property
    def improvement_direction(self) -> str:
        """Human-readable direction string."""
        if self.reward_delta > 0.05:
            return "strong_improvement (+)"
        elif self.reward_delta >= 0.0:
            return "improvement (+)"
        elif self.reward_delta > -0.05:
            return "slight_degradation (-)"
        else:
            return "strong_degradation (-)"

    def to_dict(self) -> dict[str, Any]:
        return {
            "cycle": self.cycle,
            "action": json.loads(self.action.to_json()),
            "acceptance_rate_before": self.acceptance_rate_before,
            "acceptance_rate_after": self.acceptance_rate_after,
            "reward_delta": self.reward_delta,
            "examples_generated": self.examples_generated,
            "inner_train_loss": self.inner_train_loss,
            "inner_eval_loss": self.inner_eval_loss,
            "improvement_direction": self.improvement_direction,
            "timestamp": self.timestamp,
        }


@dataclass
class SealConfig:
    """Configuration for the SEAL dual-loop system."""

    # Curriculum generator settings
    curriculum_model: str = "qwen2.5-coder:7b-instruct-q4_K_M"
    """Ollama model used to generate curriculum decisions."""

    curriculum_temperature: float = 0.8
    """Temperature for curriculum generation (higher = more exploration)."""

    # Inner loop settings
    inner_model: str = "qwen2.5-coder:7b-instruct-q4_K_M"
    """Base model used in the inner SFT loop."""

    inner_synthetic_model: str = "qwen2.5-coder:7b-instruct-q4_K_M"
    """Model used to generate synthetic training data."""

    inner_lora_rank: int = 16
    """LoRA rank for inner loop training."""

    inner_learning_rate: float = 2e-4
    """Learning rate for inner loop training."""

    inner_max_steps: int = 100
    """Max training steps per inner loop."""

    inner_batch_size: int = 2
    """Batch size for inner loop training."""

    inner_max_length: int = 2048
    """Max sequence length for inner loop."""

    # Synthetic data settings
    synthetic_examples_per_action: int = 30
    """Default number of synthetic examples to generate per action."""

    synthetic_augmentation_factor: int = 3
    """Generate N variations of each real example."""

    # Outer loop settings
    outer_min_cycle_interval_hours: float = 6.0
    """Minimum time between outer loop cycles."""

    outer_min_acceptance_samples: int = 50
    """Minimum number of accept/reject events needed for a reliable rate."""

    outer_acceptance_window_hours: float = 24.0
    """Window of events to use for acceptance rate calculation."""

    # Meta-learning settings
    meta_enabled: bool = True
    """Whether to fine-tune the curriculum generator."""

    meta_lora_rank: int = 8
    """LoRA rank for curriculum generator fine-tuning."""

    meta_learning_rate: float = 5e-5
    """Learning rate for meta-learning."""

    meta_min_rewards_for_training: int = 3
    """Minimum reward records before meta-learning activates."""

    # Paths
    state_dir: str = ".forgeai/seal"
    """Directory for persisting SEAL state."""

    adapter_dir: str = "checkpoints/seal_adapters"
    """Directory for inner loop adapter outputs."""

    curriculum_adapter_dir: str = "checkpoints/seal_curriculum"
    """Directory for meta-learned curriculum adapter."""

    synthetic_data_dir: str = "data/seal_synthetic"
    """Directory for generated synthetic training data."""

    # Exploration-exploitation
    exploration_rate: float = 0.3
    """Probability of choosing a random action instead of the best-known one."""

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> SealConfig:
        valid_keys = set(cls.__dataclass_fields__.keys())
        filtered = {k: v for k, v in data.items() if k in valid_keys}
        return cls(**filtered)

    def to_dict(self) -> dict[str, Any]:
        return {k: getattr(self, k) for k in self.__dataclass_fields__}
